Services/Navitia.php
Related to meth-540, to get 'administrative_regions' of a route/stop_point direction
RELATES TO https://github.com/CanalTP/MttBundle/pull/50
=> adding depth to route request

.gitignore, Features/Context/FeatureContext.php, Features/Scenarios/homepage.feature, composer.json
*Simple Behat test added*
*Now Unit & behat tests will be launched by Jenkins.*
*Execute command:*
```javascript
php composer.phar install
./vendor/bin/phpunit --testsuite=NmmPortal
```
=> Feature test and jenkins

Entity/Customer.php, Features/Context/FeatureContext.php, Features/Scenarios/homepage.feature, Migrations/pdo_pgsql/Version003.php, Resources/config/doctrine/Customer.orm.yml, composer.json
We need to do a link between NMM customers and users Fenrir. This migration add "fenrir_id" column in table customers and create users in fenrir-api with identifier of customer.
Depends of:
```
php app/console claroline:migration:upgrade CanalTPNmmPortalBundle
php app/console claroline:migration:downgrade CanalTPNmmPortalBundle
=> New migration: fenrir_id column added.

Controller/CustomerController.php, Features/Scenarios/Customer/list.feature, Features/Scenarios/Customer/show.feature, Resources/config/routing.yml, Resources/translations/messages.fr.yml, Resources/views/Customer/list.html.twig, Resources/views/Customer/show.html.twig
*List of customer updated (edit button added)*
*Show page of customer created*
*Execute command:*
```javascript
php composer.phar install
./vendor/bin/phpunit --testsuite=NmmPortal
```
Depends of:
=> Refs #NAVIO-602 ~ Show page of customer implemented.

composer.json
In this PR we remove fenrir bundle reference in composer file.
=> Configuration of composer updated. (fenrir bundle removed.)

Entity/PerimeterRepository.php
Fetch networks id by external coverage id and application name
=> Fetch networks id by external coverage id and application name

CanalTPNmmPortalBundle.php
fix sam:database:reset doesn't run nmm-portal migrations
```
app/console sam:database:reset
```
=> Fix nmm-portal migrations not run

Resources/views/Customer/form.html.twig, Resources/views/NavitiaUser/form.html.twig, Resources/views/Sam/index.html.twig
https://github.com/CanalTP/NmmPortalBundle/issues/29
Extending possible missing views files.
This is a bug fix.
Install NMM from scratch without any other bundles.
=> twig: fix base default views extending

composer.json
This PR upgrade requirements for timezone support
related to https://github.com/CanalTP/SamCoreBundle/pull/38
=> upgrade requirements for timezone support

composer.json
This PR forces SamCoreBundle update to >= 1.6 since this is needed to actually remove the tab
- Jenkins build must pass
NMM Guilde
=> Update SamCore version dependency

Resources/views/config.js.html.twig
This PR update the configuration of requireJS.
Issue link: https://github.com/CanalTP/NMM/issues/336
=> Refs #BOT-371 ~ Configuration of requireJS updated.

Resources/views/Customer/list.html.twig
This PR fix the sorting malfunction of the creation date column
Issue link: BOT-383
Issue NMM : https://github.com/CanalTP/NMM/issues/335
- Go to the client page (with admin NMM login)
- Check if the sorting effect of the creation date column is correct
=> Fix sorting on date

Resources/public/css/main.css
This PR fixes css for https://github.com/CanalTP/SamCoreBundle/pull/43
Issue link: GN-55
https://github.com/CanalTP/NMM/issues/338
go in admin on every page, see difference
=> new menu display

Resources/public/css/main.css, Resources/views/Customer/form.html.twig
This PR fixes CSS on NMM customer edition
=> Minor alignments

Controller/CustomerController.php, Resources/config/routing.yml, Resources/public/js/form/client.js, Resources/translations/messages.fr.yml, Resources/views/Customer/_deleteModalContent.html.twig, Resources/views/Customer/deleteClientModal.html.twig, Resources/views/Customer/form.html.twig, Resources/views/Customer/list.html.twig, Resources/views/config.js.html.twig
This PR adds remove button on client list page
Issue link: BOT-442
This is a bug new feature
=> Adding remove button on cliet list interface

Resources/public/css/main.css, Resources/views/Customer/list.html.twig
This PR to keep logic thru all pages + minor html editions
Connected as super user
See action button display thru all NMM menus (users, clients, roles lists)
Related to https://github.com/CanalTP/SamEcoreSecurityManagerBundle/pull/8
=> Minor style Actions

Resources/public/js/tracking.js, Resources/views/config.js.html.twig
This PR add a class for push event with datalayer
Issue link: BOT-756
=> Add tracking datalayer push global class

Resources/views/config.js.html.twig
=> New library (JS) implemented (timeago)

Migrations/pdo_pgsql/Version003.php
This PR change the default route when login to TR into the dashboard page (impact list)
Issue link: BOT-1153
- Log into TR
- You should be on the new dashboard page
=> Update default homepage for TR

DataFixtures/ORM/FixturesCustomer.php, Features/Scenarios/Customer/list.feature
This PR fixes creation customer on load fixture
https://github.com/CanalTP/NMM/blob/master/bin/run-tests-nmmportal.sh
=> Fix Test - Doublon create customer fixture

Entity/Language.php
This PR add __toString function to language entity.
Issue link: bot-1437
related to https://github.com/CanalTP/SamEcoreUserManagerBundle/pull/31
=> Add __toString function to language entity

Entity/Customer.php, Tests/Units/Entity/CustomerTest.php
This PR fixes bug on create new customer: X-contributor not found
Issue link: BOT-1400
=> #BOT-1400 - Add method get contributor

Resources/public/js/gtracking.js, Resources/views/config.js.html.twig
This PR fixes tracking.js bug on require.js 
Issue link: BOT-1809
=> [bug Autocomplete TR] Fixing tracking import error in requirejs

Controller/CustomerController.php, Entity/NavitiaEntity.php, Form/Type/NavitiaEntityType.php, Tests/Units/CustomerTranslatorTest.php
This PR fixes unit test
Issue link: BOT-1760
=> #BOT-1760 - Fix tests unit

.gitignore, Features/Context/FeatureContext.php, Jenkinsfile, README.md, Tests/Units/Entity/CustomerTest.php, Tests/Units/Entity/LanguageTest.php, Tests/Units/EntityBase.php, docker-compose.test.yml, docker/Dockerfile.test, docker/apache.conf, docker/run_functional_test.sh, docker/wait-for-it.sh, phpunit.xml.dist
This PR add the jenkinsfile in order to launch test with the new jenkins
Issue link: BOT-2046
- launch in https://jenkins-bot.canaltp.fr/job/nmm-portal-bundle%20(github)/ a build with sha1 = task-bot-2046-add-jenkinsfile
**OR**
- test in local, see [README.md](https://github.com/CanalTP/NmmPortalBundle/blob/9025353979fd264158045b5da81e651402ff5eb5/README.md)
https://github.com/CanalTP/NMM/pull/425
=> Add jenkinsfile

docker-compose.test.yml
Remove useless service memcached
=> Remove useless service memcached
